apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectionservice/deployment.yaml
  - connectionservice/service.yaml

  - apigateway/deployment.yaml
  - apigateway/service.yaml
  - apigateway/route.yaml